version: '3'
services:
    app:     
        container_name: 'gooo_app'
        restart: always
        build: .  
        ports:
        - '3001:3001'
        tty: true
        links:
            - mongodb
    mongodb:
        image: mongo
        container_name: 'mongo'
        ports:
            - 27017:27017

