version: '2.2'
services:
  api:
    container_name: api
    image: gooo:latest
    ports:
      - 8080:8080
    depends_on:
        mongo:
          condition: service_healthy
  web:
    container_name: web
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - api
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27100:27017
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017 --quiet
      interval: 10s
      timeout: 25s
      retries: 1
    command: mongod --smallfiles